package com.jmopsagent.domain;

public enum EvidenceType {
    TRACKING_EVENT,
    CALL_CHAIN,
    ERROR_LOG,
    LOG_PATTERN,
    TRAFFIC_SUMMARY,
    RECENT_BUSINESS_CALLS,
    WORKLOAD_HEALTH,
    POD_EVENT,
    POD_LOG,
    DEPLOYMENT_METADATA,
    BUILD,
    BUILD_CHANGE,
    CONFIGURATION,
    ROUTE,
    INSTANCE_STATUS,
    COMMIT,
    COMMIT_DIFF,
    SOURCE_CODE,
    DEPENDENCY_STATUS,
    RUNBOOK_EXCERPT,
    HISTORICAL_MATCH,
    OTHER
}
